# Key unik untuk project ini di SonarQube (bebas tapi tanpa spasi)
sonar.projectKey=simple-apps

# Nama yang akan muncul di dashboard SonarQube
sonar.projectName=simple-apps

# Versi project kamu
sonar.projectVersion=1.0

# Lokasi source code yang akan discan (titik (.) berarti semua folder saat ini)
sonar.sources=.

#Tambahkan baris ini untuk ignore folder/file
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.test.js
